# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "products-app"
client_id = "60d8381b2ac9c684114d71f416e16640"
application_url = "https://drop-arrest-cabinets-characteristics.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://drop-arrest-cabinets-characteristics.trycloudflare.com/auth/callback",
  "https://drop-arrest-cabinets-characteristics.trycloudflare.com/auth/shopify/callback",
  "https://drop-arrest-cabinets-characteristics.trycloudflare.com/api/auth/callback",
  "https://drop-arrest-cabinets-characteristics.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wr-test-app.myshopify.com"
